services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=book_review'
      - 'MYSQL_PASSWORD=fcKd6aJS8A'
      - 'MYSQL_ROOT_PASSWORD=07102004'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
